#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: ['GET', 'POST']

profile:
    path: /profile
    controller: App\Controller\ProfileController::index