<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLRiHc2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLRiHc2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRLRiHc2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRLRiHc2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRLRiHc2\App_KernelDevDebugContainer([
    'container.build_hash' => 'RLRiHc2',
    'container.build_id' => 'b9ba97db',
    'container.build_time' => 1714031924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLRiHc2');
