<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Dw8fvA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Dw8fvA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8Dw8fvA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8Dw8fvA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8Dw8fvA\App_KernelDevDebugContainer([
    'container.build_hash' => '8Dw8fvA',
    'container.build_id' => 'f7e1b283',
    'container.build_time' => 1713967009,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Dw8fvA');
