<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEgjHmfm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEgjHmfm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEgjHmfm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEgjHmfm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEgjHmfm\App_KernelDevDebugContainer([
    'container.build_hash' => 'EgjHmfm',
    'container.build_id' => '6127e945',
    'container.build_time' => 1713908437,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEgjHmfm');
